version: '3.8'

services:
  app:
    container_name: nextjs-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production

